{{- $commonLabels := include "vault-secret.labels" . }}
{{- range .Values.secrets }}

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .name }}
  labels:
    {{- $commonLabels | nindent 4 }}
spec:
  type: kv-v2
  mount: kv
  path: {{ .path }}

  # dest k8s secret
  destination:
    name: {{ .destination }}
    create: true
    {{- if  .labels }}
    labels:
      {{- toYaml .labels | nindent 6 }}
    {{- end }}
    {{- if  .transformation }}
    transformation:
      {{- toYaml .transformation | nindent 6 }}
    {{- end }}

  # static secret refresh interval
  refreshAfter: {{ default "30s" .refreshAfter }}

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vault-static-auth
{{- end }}
